"""Unit tests for doc_formatter_agent — deterministic formatting steps."""
from __future__ import annotations

import pytest
from agents.doc_formatter import _build_meta_table, doc_formatter_agent


class TestBuildMetaTable:
    def test_build_meta_table_requirements(self):
        result = _build_meta_table("TestProject", "requirements")
        assert "TestProject" in result
        assert "需求分析文档" in result
        assert "| **项目名称**" in result
        assert "V1.0" in result

    def test_build_meta_table_architecture(self):
        result = _build_meta_table("TestProject", "architecture")
        assert "架构设计文档" in result

    def test_build_meta_table_testing(self):
        result = _build_meta_table("TestProject", "testing")
        assert "测试文档" in result

    def test_build_meta_table_unknown_type(self):
        result = _build_meta_table("TestProject", "custom")
        assert "custom" in result


class TestDocFormatterAgent:
    def _run(self, doc_draft: str, doc_type: str = "requirements",
             project_name: str = "TestProject") -> dict:
        state = {"doc_draft": doc_draft, "doc_type": doc_type,
                 "project_name": project_name, "trace": []}
        return doc_formatter_agent(state)

    def test_formatted_field_set(self):
        result = self._run("# Test Document\nSome content.")
        assert "doc_formatted" in result

    def test_meta_table_inserted_when_missing(self):
        result = self._run("# Test\nContent")
        assert "| **项目名称** | TestProject |" in result["doc_formatted"]

    def test_meta_table_not_duplicated(self):
        existing = "| **项目名称** | Already |\n# Test\n"
        result = self._run(existing)
        assert result["doc_formatted"].count("| **项目名称** |") == 1

    def test_ai_declaration_appended(self):
        result = self._run("# Test\nContent without declaration.")
        assert "DocGen Agent 自动生成" in result["doc_formatted"]

    def test_ai_declaration_not_duplicated(self):
        existing = "# Test\nContent\n*本文档由 DocGen Agent 自动生成，状态为草稿，需人工审核确认。*"
        result = self._run(existing)
        assert result["doc_formatted"].count("DocGen Agent 自动生成") == 1

    def test_english_declaration_not_duplicated(self):
        existing = "# Test\nContent\n*automatically generated by DocGen*"
        result = self._run(existing)
        assert "automatically generated by DocGen" in result["doc_formatted"]

    def test_trace_updated(self):
        result = self._run("# Test\nContent")
        assert len(result["trace"]) == 1
        assert result["trace"][0]["node"] == "doc_formatter"

    def test_heading_spacing(self):
        """## headings should be surrounded by blank lines."""
        result = self._run("# Test\n## Section1\nText\n## Section2")
        assert "doc_formatted" in result
