from tools.trace import append_trace


def doc_reviewer_agent(state):
    """
    审核生成的文档，检查格式规范、章节完整性、是否有占位符等。
    参照 docs/doc_spec.md 中「文档质量检查清单」逐项检查。
    这是确定性检查步骤，不依赖 LLM。
    """
    doc = state.get("doc_formatted", "")
    doc_type = state.get("doc_type", "requirements")
    language = state.get("language", "zh")

    checks = []

    # CHK-01: 文档元信息表
    has_meta = "| **项目名称**" in doc or "| **Project Name**" in doc
    checks.append({"check": "CHK-01", "item": "文档元信息表", "passed": has_meta,
                   "detail": "存在" if has_meta else "缺失"})

    # CHK-02: 必须章节检查（按类型，模糊匹配）
    required_sections = _get_required_sections(doc_type)
    for section in required_sections:
        found = _section_exists(doc, section)
        checks.append({"check": "CHK-02", "item": f"章节: {section}", "passed": found,
                       "detail": "存在" if found else "缺失"})

    # CHK-05: 无占位符检查
    placeholders = ["TODO", "TBD", "待定", "待补充", "TKTK", "XXX"]
    has_placeholders = []
    for ph in placeholders:
        if ph in doc:
            has_placeholders.append(ph)
    checks.append({"check": "CHK-05", "item": "无占位符", "passed": len(has_placeholders) == 0,
                   "detail": f"发现占位符: {has_placeholders}" if has_placeholders else "通过"})

    # CHK-06: 语言一致性
    if language == "zh":
        english_keywords = 0
        en_markers = ["Introduction", "Overview", "Architecture", "Testing", "Requirements", "Design",
                      "Implementation", "Deployment", "Security", "Performance"]
        for marker in en_markers:
            if f"## {marker}" in doc or f"### {marker}" in doc:
                english_keywords += 1
        passed_lang = english_keywords <= 2
        checks.append({"check": "CHK-06", "item": "语言一致性", "passed": passed_lang,
                       "detail": f"{'通过' if passed_lang else f'发现{english_keywords}个英文标题'}"})
    else:
        checks.append({"check": "CHK-06", "item": "语言一致性", "passed": True, "detail": "通过"})

    # CHK-07: 结尾 AI 声明
    has_ending = "DocGen Agent 自动生成" in doc or "automatically generated by DocGen" in doc
    checks.append({"check": "CHK-07", "item": "AI 生成声明", "passed": has_ending,
                   "detail": "存在" if has_ending else "缺失"})

    # CHK-04: 编号连续性（FR 或 TC）
    if doc_type == "requirements":
        fr_numbers = _extract_numbers(doc, "FR-")
        has_gaps = _check_gaps(fr_numbers, "FR-")
    elif doc_type == "testing":
        fr_numbers = _extract_numbers(doc, "TC-")
        has_gaps = _check_gaps(fr_numbers, "TC-")
    else:
        has_gaps = False
    checks.append({"check": "CHK-04", "item": "编号连续性",
                   "passed": not has_gaps,
                   "detail": "通过" if not has_gaps else f"编号不连续"})

    # 汇总
    passed_count = sum(1 for c in checks if c["passed"])
    total_count = len(checks)
    all_passed = passed_count == total_count

    review_report = {
        "passed": all_passed,
        "passed_count": passed_count,
        "total_count": total_count,
        "checks": checks,
        "summary": f"{passed_count}/{total_count} 项检查通过" + (" ✓" if all_passed else " ✗"),
    }

    # 如果审核通过，标记为最终文档；否则保留格式化版本
    if all_passed:
        state["doc_final"] = doc
    else:
        state["doc_final"] = doc + f"\n\n<!-- Review failed: {review_report['summary']} -->"

    state["review_report"] = review_report
    append_trace(state, "doc_reviewer", review_report["summary"])
    return state


def _get_required_sections(doc_type: str) -> list[str]:
    """返回各文档类型必须包含的章节标题。"""
    # 注意：文档元信息表由 CHK-01 独立检查，不在此重复
    common: list[str] = []
    if doc_type == "requirements":
        return common + [
            "## 1. 引言", "## 2. 系统概述", "## 3. 用户需求分析",
            "## 4. 功能需求", "## 5. 非功能需求", "## 6. 数据需求",
            "## 7. 外部接口需求", "## 8. 约束与假设",
        ]
    elif doc_type == "architecture":
        return common + [
            "## 1. 总体架构", "## 2. 模块划分", "## 3. 数据流设计",
            "## 4. 组件/服务通信", "## 5. 技术选型", "## 6. 部署架构",
            "## 7. 安全设计",
        ]
    else:  # testing
        return common + [
            "## 1. 测试策略", "## 2. 单元测试方案", "## 3. 集成测试方案",
            "## 4. 系统测试方案", "## 5. 验收测试方案", "## 6. 测试环境",
            "## 7. 缺陷管理",
        ]


def _extract_numbers(text: str, prefix: str) -> list[int]:
    """从文本中提取指定前缀的数字编号。"""
    import re
    pattern = re.escape(prefix) + r"(\d+)"
    nums = [int(m) for m in re.findall(pattern, text)]
    return sorted(set(nums))


def _check_gaps(numbers: list[int], prefix: str) -> bool:
    """检查编号是否有跳号。返回 True 表示有跳号。"""
    if not numbers:
        return True
    expected = list(range(numbers[0], numbers[-1] + 1))
    return numbers != expected


def _section_exists(doc: str, expected: str) -> bool:
    """检查文档中是否存在预期的章节标题（支持模糊匹配）。
    兼容：
      - ## 1. 总体架构   (标准格式)
      - ## 一、总体架构   (中文编号)
      - ## 总体架构       (无编号)
    """
    if expected in doc:
        return True

    # 提取核心名称：去掉 ##  和 编号前缀（兼容 "1. ", "一、", "1 " 等）
    import re
    _STRIP_PREFIX = re.compile(r'^##\s*(?:\d+[\.、\s]*|[一二三四五六七八九十]+[、\s]*)?')
    core = _STRIP_PREFIX.sub('', expected).strip()
    if not core:
        return False

    # 扫描文档中所有 ## 标题，做同样处理后比较
    for line in doc.split('\n'):
        stripped = line.strip()
        if stripped.startswith('## '):
            heading_core = _STRIP_PREFIX.sub('', stripped).strip()
            if heading_core == core:
                return True

    return False
