from tools.trace import append_trace


def tc_formatter_agent(state):
    """
    对测试用例初稿进行格式化处理：
    - 确保 Markdown 表格对齐
    - 确保章节编号连续
    - 添加文档元信息表（如果缺失）
    - 移除可能的占位符
    这是确定性格式化步骤，不依赖 LLM。
    """
    draft = state.get("tc_draft", "")
    tc_type = state.get("tc_type", "normal")
    project_name = state.get("project_name", "MedReasonerAgent")

    formatted = draft

    tc_type_names = {
        "normal": "正常场景测试用例",
        "boundary": "边界场景测试用例",
        "abnormal": "异常场景测试用例",
    }

    # 1. 确保文档元信息表存在
    if "| **项目名称**" not in draft and "| **Project Name**" not in draft:
        header = _build_meta_table(project_name, tc_type_names.get(tc_type, tc_type), tc_type)
        # 插入到主标题之后
        lines = formatted.split("\n")
        for i, line in enumerate(lines):
            if line.startswith("# ") and i + 1 < len(lines):
                lines.insert(i + 1, "")
                lines.insert(i + 2, header)
                break
        formatted = "\n".join(lines)

    # 2. 确保结尾声明存在
    ai_declaration = "\n\n---\n\n*本文档由 TCGen Agent 自动生成，状态为草稿，需人工审核确认。*"
    if "TCGen Agent 自动生成" not in formatted and "automatically generated by TCGen" not in formatted:
        formatted = formatted.rstrip() + ai_declaration

    # 3. 基本规范化：统一空格、去除末尾空白
    formatted = "\n".join(line.rstrip() for line in formatted.split("\n"))

    # 4. 剔除 LLM 多生成的冗余元信息行（含"审核人 | 待定"等）
    lines = formatted.split("\n")
    cleaned_lines = []
    skip = False
    for line in lines:
        if ("| 审核人" in line or "| 批准人" in line or "| 评审人" in line) and "待定" in line:
            skip = True
            continue
        if skip:
            if line.strip() == "" or line.strip().startswith("|"):
                continue
            skip = False
        cleaned_lines.append(line)
    formatted = "\n".join(cleaned_lines)
    # 额外兜底：直接替换残留的待定行
    formatted = formatted.replace("| 审核人 | 待定 |\n", "")
    formatted = formatted.replace("| 批准人 | 待定 |\n", "")
    formatted = formatted.replace("| 评审人 | 待定 |\n", "")

    # 5. 确保各级标题前后有空行
    lines = formatted.split("\n")
    result = []
    for i, line in enumerate(lines):
        if line.startswith("## ") or line.startswith("### ") or line.startswith("#### "):
            if result and result[-1] != "":
                result.append("")
            result.append(line)
            result.append("")
        else:
            result.append(line)
    formatted = "\n".join(result)

    state["tc_formatted"] = formatted
    append_trace(state, "tc_formatter", f"Formatted test cases ({len(formatted)} chars)")
    return state


def _build_meta_table(project_name: str, type_name: str, tc_type: str) -> str:
    from datetime import date
    return f"""| 属性 | 内容 |
|------|------|
| **项目名称** | {project_name} |
| **文档类型** | {type_name} |
| **文档版本** | V1.0 |
| **生成日期** | {date.today().isoformat()} |
| **生成方式** | AI 自动生成（TCGen Agent） |
| **状态** | 草稿 |
| **DRG 版本** | 基于项目内置 DRG 知识图谱 |
"""
