from tools.trace import append_trace


def tc_reviewer_agent(state):
    """
    审核生成的测试用例文档，检查格式规范、章节完整性、是否有占位符等。
    参照 docs/tc_spec.md 中「文档质量检查清单」逐项检查。
    这是确定性检查步骤，不依赖 LLM。
    """
    doc = state.get("tc_formatted", "")
    tc_type = state.get("tc_type", "normal")
    language = state.get("language", "zh")

    checks = []

    # CHK-01: 文档元信息表
    has_meta = "| **项目名称**" in doc or "| **Project Name**" in doc
    checks.append({"check": "CHK-01", "item": "文档元信息表", "passed": has_meta,
                   "detail": "存在" if has_meta else "缺失"})

    # CHK-02: 必须章节检查
    required_sections = _get_required_sections(tc_type)
    for section in required_sections:
        found = _section_exists(doc, section)
        checks.append({"check": "CHK-02", "item": f"章节: {section}", "passed": found,
                       "detail": "存在" if found else "缺失"})

    # CHK-05: 无占位符检查
    # "XXX" 在测试用例中是合法的无效编码测试数据（如 XXXX.X），
    # 仅当作为独立占位符词（不嵌在编码/JSON 中）时才标记
    placeholders = ["TODO", "TBD", "待定", "待补充", "TKTK"]
    has_placeholders = []
    for ph in placeholders:
        if ph in doc:
            has_placeholders.append(ph)
    # XXX 特殊处理：排除 JSON 块内和编码模式中的出现
    xxx_invalid = _check_xxx_standalone(doc)
    if xxx_invalid:
        has_placeholders.append("XXX (独立占位)")
    checks.append({"check": "CHK-05", "item": "无占位符", "passed": len(has_placeholders) == 0,
                   "detail": f"发现占位符: {has_placeholders}" if has_placeholders else "通过"})

    # CHK-06: 语言一致性
    if language == "zh":
        english_keywords = 0
        en_markers = ["Introduction", "Overview", "Test", "Design", "Analysis", "Data",
                      "Implementation", "Strategy", "Boundary", "Abnormal", "Scenario"]
        for marker in en_markers:
            if f"## {marker}" in doc or f"### {marker}" in doc:
                english_keywords += 1
        passed_lang = english_keywords <= 2
        checks.append({"check": "CHK-06", "item": "语言一致性", "passed": passed_lang,
                       "detail": f"{'通过' if passed_lang else f'发现{english_keywords}个英文标题'}"})
    else:
        checks.append({"check": "CHK-06", "item": "语言一致性", "passed": True, "detail": "通过"})

    # CHK-07: 结尾 AI 声明
    has_ending = "TCGen Agent 自动生成" in doc or "automatically generated by TCGen" in doc
    checks.append({"check": "CHK-07", "item": "AI 生成声明", "passed": has_ending,
                   "detail": "存在" if has_ending else "缺失"})

    # CHK-04: 编号连续性
    if tc_type == "normal":
        tc_numbers = _extract_numbers(doc, "TC-N-")
        has_gaps = _check_gaps(tc_numbers, "TC-N-")
    elif tc_type == "boundary":
        tc_numbers = _extract_numbers(doc, "TC-B-")
        has_gaps = _check_gaps(tc_numbers, "TC-B-")
    else:
        tc_numbers = _extract_numbers(doc, "TC-A-")
        has_gaps = _check_gaps(tc_numbers, "TC-A-")
    checks.append({"check": "CHK-04", "item": "编号连续性",
                   "passed": not has_gaps,
                   "detail": "通过" if not has_gaps else f"编号不连续"})

    # CHK-08: 病历 JSON 完整性（检查是否包含 JSON 代码块）
    json_block_count = doc.count('```json')
    min_expected = 6 if tc_type == "normal" else (5 if tc_type == "boundary" else 5)
    has_enough_json = json_block_count >= min_expected
    checks.append({"check": "CHK-08", "item": "病历 JSON 完整",
                   "passed": has_enough_json,
                   "detail": f"发现 {json_block_count} 个 JSON 块" if has_enough_json
                   else f"仅 {json_block_count} 个 JSON 块，建议 ≥{min_expected}"})

    # CHK-09: 用例数量达标
    if tc_type == "normal":
        tc_count = len(_extract_numbers(doc, "TC-N-"))
        min_required = 6
    elif tc_type == "boundary":
        tc_count = len(_extract_numbers(doc, "TC-B-"))
        min_required = 6
    else:
        tc_count = len(_extract_numbers(doc, "TC-A-"))
        min_required = 6
    checks.append({"check": "CHK-09", "item": "用例数量达标",
                   "passed": tc_count >= min_required,
                   "detail": f"发现 {tc_count} 个测试用例，要求 ≥{min_required}"})

    # 汇总
    passed_count = sum(1 for c in checks if c["passed"])
    total_count = len(checks)
    all_passed = passed_count == total_count

    review_report = {
        "passed": all_passed,
        "passed_count": passed_count,
        "total_count": total_count,
        "checks": checks,
        "summary": f"{passed_count}/{total_count} 项检查通过" + (" ✓" if all_passed else " ✗"),
    }

    # 如果审核通过，标记为最终文档；否则保留格式化版本
    if all_passed:
        state["tc_final"] = doc
    else:
        state["tc_final"] = doc + f"\n\n<!-- Review failed: {review_report['summary']} -->"

    state["review_report"] = review_report
    append_trace(state, "tc_reviewer", review_report["summary"])
    return state


def _get_required_sections(tc_type: str) -> list[str]:
    """返回各测试类型必须包含的章节标题。"""
    if tc_type == "normal":
        return [
            "## 1. 测试概述", "## 2. DRG 分组规则摘要",
            "## 3. 测试场景设计", "## 4. 测试用例", "## 5. 测试数据",
        ]
    elif tc_type == "boundary":
        return [
            "## 1. 测试概述", "## 2. 边界条件分析",
            "## 3. 测试场景设计", "## 4. 测试用例", "## 5. 测试数据",
        ]
    else:  # abnormal
        return [
            "## 1. 测试概述", "## 2. 异常条件分析",
            "## 3. 测试场景设计", "## 4. 测试用例", "## 5. 测试数据",
        ]


def _check_xxx_standalone(doc: str) -> bool:
    """检查文档中是否存在作为独立占位符的 XXX。
    排除以下合法场景：
    - JSON 代码块内的 XXX（如 "code": "XXXX.X"）
    - 编码模式中的 XXX（如 XXXX.X、XXX-XX）
    返回 True 表示存在不应出现的独立 XXX 占位符。
    """
    import re

    # 移除所有 JSON 代码块内容
    cleaned = re.sub(r'```json\b.*?```', '', doc, flags=re.DOTALL)
    # 移除所有代码块内容
    cleaned = re.sub(r'```[a-z]*\b.*?```', '', cleaned, flags=re.DOTALL)

    # 移除编码模式中的 XXX（如 XXXX.X, XXX-XX, TC-XXX-01 等）
    # 只剥离含非 X 字符的编码 token，保留纯 XXX 占位符
    def _is_code_pattern(m: re.Match) -> bool:
        """仅当匹配包含非 X 字符时才视为编码模式（而非占位符）。"""
        return any(ch != 'X' for ch in m.group())

    cleaned = re.sub(
        r'\b[A-Z0-9]*X{2,}[A-Z0-9.-]*\b',
        lambda m: '' if _is_code_pattern(m) else m.group(),
        cleaned,
    )

    # 检查剩余文本中是否还有独立的 XXX（作为占位符）
    return 'XXX' in cleaned


def _extract_numbers(text: str, prefix: str) -> list[int]:
    """从文本中提取指定前缀的数字编号。"""
    import re
    pattern = re.escape(prefix) + r"(\d+)"
    nums = [int(m) for m in re.findall(pattern, text)]
    return sorted(set(nums))


def _check_gaps(numbers: list[int], prefix: str) -> bool:
    """检查编号是否有跳号。返回 True 表示有跳号。"""
    if not numbers:
        return True
    expected = list(range(numbers[0], numbers[-1] + 1))
    return numbers != expected


def _section_exists(doc: str, expected: str) -> bool:
    """检查文档中是否存在预期的章节标题（支持模糊匹配）。"""
    if expected in doc:
        return True

    import re
    _STRIP_PREFIX = re.compile(r'^##\s*(?:\d+[\.、\s]*|[一二三四五六七八九十]+[、\s]*)?')
    core = _STRIP_PREFIX.sub('', expected).strip()
    if not core:
        return False

    for line in doc.split('\n'):
        stripped = line.strip()
        if stripped.startswith('## '):
            heading_core = _STRIP_PREFIX.sub('', stripped).strip()
            if heading_core == core:
                return True

    return False
